# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('note', models.TextField(default='')),
                ('effective', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('note', models.TextField(default='')),
                ('effective', models.DateField(db_index=True)),
                ('source_id', models.IntegerField()),
                ('source_category', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('note', models.TextField(default='')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('category', models.IntegerField(choices=[(0, 'Principal cliente'), (2, 'Balanço cliente'), (4, 'Não contábil cliente'), (6, 'Cobrança cliente'), (8, 'Pagamento cliente'), (9, 'Imposto cliente'), (1, 'Principal sistema'), (3, 'Balanço sistema'), (5, 'Não contábil sistema'), (7, 'Cobrança sistema')])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subaccounts', to='core.Ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('source_id', 'source_category')]),
        ),
        migrations.AddField(
            model_name='entry',
            name='credited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.Ledger'),
        ),
        migrations.AddField(
            model_name='entry',
            name='debited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='core.Ledger'),
        ),
        migrations.AddField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.Event'),
        ),
    ]
