# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:16
from __future__ import unicode_literals

from django.db import migrations
from psycopg2.extensions import AsIs

from common.db.operations import temporal_table
from core.models import Event, Entry


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = temporal_table(Event) + temporal_table(Entry)
