# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:45
from __future__ import unicode_literals

from django.db import migrations

from common.db.operations import temporal_table
from core.models import Entry, Event


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = temporal_table(Event) + temporal_table(Entry)
