# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:46
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations import state
from django.db.backends.base import schema
from django.utils.text import slugify

from ..const import (
    LEDGER_SYSTEM_BALANCE,
    LEDGER_SYSTEM_CHARGE,
    LEDGER_SYSTEM_EXTRA,
    LEDGER_SYSTEM_MAIN
)


def create_system_ledger(
        apps: migrations.state.StateApps,
        schema_editor: schema.BaseDatabaseSchemaEditor):
    Ledger = apps.get_model('core', 'Ledger')
    instance = Ledger(
        name='System Main',
        category=LEDGER_SYSTEM_MAIN
    )
    instance.slug = slugify(instance.name)
    instance.save()

    confs = (
        ('System Balance', LEDGER_SYSTEM_BALANCE),
        ('System Extra', LEDGER_SYSTEM_EXTRA),
        ('System Charge', LEDGER_SYSTEM_CHARGE),
    )
    instances = [
        Ledger(name=n, slug=slugify(n), category=c, parent=instance)
        for n, c in confs
        ]
    Ledger.objects.bulk_create(instances)


def delete_system_ledger(
        apps: migrations.state.StateApps,
        schema_editor: schema.BaseDatabaseSchemaEditor):
    Ledger = apps.get_model('core', 'Ledger')
    categories = (
        LEDGER_SYSTEM_BALANCE,
        LEDGER_SYSTEM_CHARGE,
        LEDGER_SYSTEM_EXTRA,
        LEDGER_SYSTEM_MAIN
    )
    Ledger.objects.filter(category__in=categories).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_metadata_index'),
    ]

    operations = [
        migrations.RunPython(
            code=create_system_ledger,
            reverse_code=delete_system_ledger
        )
    ]
