# encoding: utf-8
LEDGER_CUSTOMER_MAIN = 0
LEDGER_SYSTEM_MAIN = 1
LEDGER_CUSTOMER_BALANCE = 2
LEDGER_SYSTEM_BALANCE = 3
LEDGER_CUSTOMER_EXTRA = 4
LEDGER_SYSTEM_EXTRA = 5
LEDGER_CUSTOMER_CHARGE = 6
LEDGER_SYSTEM_CHARGE = 7
LEDGER_CUSTOMER_PAYMENT = 8
LEDGER_CUSTOMER_TAX = 9

LEDGER_CATEGORY_CHOICES = (
    (LEDGER_CUSTOMER_MAIN, 'Principal cliente'),
    (LEDGER_CUSTOMER_BALANCE, 'Balanço cliente'),
    (LEDGER_CUSTOMER_EXTRA, 'Não contábil cliente'),
    (LEDGER_CUSTOMER_CHARGE, 'Cobrança cliente'),
    (LEDGER_CUSTOMER_PAYMENT, 'Pagamento cliente'),
    (LEDGER_CUSTOMER_TAX, 'Imposto cliente'),
    (LEDGER_SYSTEM_MAIN, 'Principal sistema'),
    (LEDGER_SYSTEM_BALANCE, 'Balanço sistema'),
    (LEDGER_SYSTEM_EXTRA, 'Não contábil sistema'),
    (LEDGER_SYSTEM_CHARGE, 'Cobrança sistema'),
)
